print('Users menu OPTIONS:\n')
print('\t--initialize --')
print('(i) read all data from the input files into the necessary main variables\n')
print('\t--modification options--')
print('(a) assign flights to the airline aircraft')
print('(c) calculate current operational cost related to airports services') 
print('(d) enter a delay and check assignments\n')
print('\t--output options--')
print('(s) show airline information in the screen and the cost of the day operations') 
print('(k) write KML files of airports, flights and assignments')
print('(p) plot the flights and the assignments of the airline')
print('(w) write current airline assignment into a file\n')
print('\t--end option--')
print('(e) end program\n')
print('Please, select an option entering one of the letters:')